version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    ports:
      - 3000:80

  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    working_dir: /app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - '.:/app'
    networks:
      - app-network
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_SERVER: ${DB_HOST}
    env_file:
            - ./src/.env
    ports:
      - "3308:3306"
networks:
  app-network:
    driver: bridge